// Incidents Module
function loadIncidents() {
    const incidents = loadData('incidents') || [];
    const html = `<div class="card"><div class="card-header d-flex justify-content-between"><span>Incidents</span><button class="btn btn-sm btn-light" onclick="showIncidentForm()"><i class="fas fa-plus"></i> Add</button></div><div class="card-body"><table class="table table-striped" id="incTable"><thead><tr><th>No</th><th>Date</th><th>Location</th><th>Type</th><th>Severity</th><th>Status</th><th>Actions</th></tr></thead><tbody>${incidents.map(i => `<tr><td>${i.incNo}</td><td>${i.date}</td><td>${i.location}</td><td>${i.type}</td><td><span class="badge bg-${i.severity === 'high' ? 'danger' : 'warning'}">${i.severity}</span></td><td><span class="badge bg-info">${i.status}</span></td><td><button class="btn btn-sm btn-primary" onclick="editIncident(${i.id})"><i class="fas fa-edit"></i></button><button class="btn btn-sm btn-danger" onclick="deleteIncident(${i.id})"><i class="fas fa-trash"></i></button></td></tr>`).join('')}</tbody></table></div></div><div class="modal fade" id="incModal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5>Add Incident</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="incForm"><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Incident No</label><input type="text" class="form-control" id="incNo" required></div><div class="col-md-6 mb-3"><label class="form-label">Date</label><input type="date" class="form-control" id="incDate" required></div></div><div class="mb-3"><label class="form-label">Location</label><input type="text" class="form-control" id="incLoc" required></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Type</label><select class="form-select" id="incType" required><option>Select</option><option value="injury">Injury</option><option value="property">Property</option><option value="other">Other</option></select></div><div class="col-md-6 mb-3"><label class="form-label">Severity</label><select class="form-select" id="incSev" required><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div></div><div class="mb-3"><label class="form-label">Description</label><textarea class="form-control" id="incDesc" rows="3" required></textarea></div><button type="submit" class="btn btn-primary">Save</button></form></div></div></div></div>`;
    setTimeout(() => { if ($.fn.dataTable.isDataTable('#incTable')) { $('#incTable').DataTable().destroy(); } $('#incTable').DataTable({pageLength: 10}); }, 100);
    return html;
}
function showIncidentForm() { document.getElementById('incForm').reset(); new bootstrap.Modal(document.getElementById('incModal')).show(); }
function deleteIncident(id) { if (confirm('Sure?')) { let i = loadData('incidents'); i = i.filter(x => x.id !== id); saveData('incidents', i); showAlert('Deleted', 'success'); loadModule('incidents'); } }
document.addEventListener('DOMContentLoaded', () => { if (document.getElementById('incForm')) { document.getElementById('incForm').addEventListener('submit', (e) => { e.preventDefault(); let incidents = loadData('incidents'); incidents.push({id: Math.max(...incidents.map(x => x.id), 0) + 1, incNo: document.getElementById('incNo').value, date: document.getElementById('incDate').value, location: document.getElementById('incLoc').value, type: document.getElementById('incType').value, severity: document.getElementById('incSev').value, description: document.getElementById('incDesc').value, status: 'open'}); saveData('incidents', incidents); bootstrap.Modal.getInstance(document.getElementById('incModal')).hide(); showAlert('Saved', 'success'); loadModule('incidents'); }); } });
