// Security Logs Module
function loadSecurity() {
    const security = loadData('security') || [];
    const html = `<div class="card"><div class="card-header d-flex justify-content-between"><span>Security Logs</span><button class="btn btn-sm btn-light" onclick="showSecurityForm()"><i class="fas fa-plus"></i> Add</button></div><div class="card-body"><table class="table table-striped" id="secTable"><thead><tr><th>Date</th><th>Time</th><th>Officer</th><th>Observation</th><th>Severity</th><th>Actions</th></tr></thead><tbody>${security.map(s => `<tr><td>${s.date}</td><td>${s.time}</td><td>${s.officer}</td><td>${s.obs}</td><td><span class="badge bg-${s.severity === 'high' ? 'danger' : 'warning'}">${s.severity}</span></td><td><button class="btn btn-sm btn-danger" onclick="deleteSecurity(${s.id})"><i class="fas fa-trash"></i></button></td></tr>`).join('')}</tbody></table></div></div><div class="modal fade" id="secModal"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Add Security Log</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="secForm"><div class="mb-3"><label class="form-label">Date</label><input type="date" class="form-control" id="secDate" required></div><div class="mb-3"><label class="form-label">Time</label><input type="time" class="form-control" id="secTime" required></div><div class="mb-3"><label class="form-label">Officer</label><input type="text" class="form-control" id="secOfficer" required></div><div class="mb-3"><label class="form-label">Observation</label><textarea class="form-control" id="secObs" rows="3" required></textarea></div><div class="mb-3"><label class="form-label">Severity</label><select class="form-select" id="secSev"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><button type="submit" class="btn btn-primary">Save</button></form></div></div></div></div>`;
    setTimeout(() => { if ($.fn.dataTable.isDataTable('#secTable')) { $('#secTable').DataTable().destroy(); } $('#secTable').DataTable({pageLength: 10}); }, 100);
    return html;
}
function showSecurityForm() { document.getElementById('secForm').reset(); new bootstrap.Modal(document.getElementById('secModal')).show(); }
function deleteSecurity(id) { if (confirm('Sure?')) { let s = loadData('security'); s = s.filter(x => x.id !== id); saveData('security', s); showAlert('Deleted', 'success'); loadModule('security'); } }
document.addEventListener('DOMContentLoaded', () => { if (document.getElementById('secForm')) { document.getElementById('secForm').addEventListener('submit', (e) => { e.preventDefault(); let security = loadData('security'); security.push({id: Math.max(...security.map(x => x.id), 0) + 1, date: document.getElementById('secDate').value, time: document.getElementById('secTime').value, officer: document.getElementById('secOfficer').value, obs: document.getElementById('secObs').value, severity: document.getElementById('secSev').value}); saveData('security', security); bootstrap.Modal.getInstance(document.getElementById('secModal')).hide(); showAlert('Saved', 'success'); loadModule('security'); }); } });
