// Theft Cases Module
function loadTheft() {
    const theft = loadData('theft') || [];
    const html = `<div class="card"><div class="card-header d-flex justify-content-between"><span>Theft Cases</span><button class="btn btn-sm btn-light" onclick="showTheftForm()"><i class="fas fa-plus"></i> Add</button></div><div class="card-body"><table class="table table-striped" id="theftTable"><thead><tr><th>Case No</th><th>Date</th><th>Item</th><th>Value</th><th>Status</th><th>Actions</th></tr></thead><tbody>${theft.map(t => `<tr><td>${t.caseNo}</td><td>${t.date}</td><td>${t.item}</td><td>${t.value}</td><td><span class="badge bg-${t.status === 'resolved' ? 'success' : 'danger'}">${t.status}</span></td><td><button class="btn btn-sm btn-danger" onclick="deleteTheft(${t.id})"><i class="fas fa-trash"></i></button></td></tr>`).join('')}</tbody></table></div></div><div class="modal fade" id="theftModal"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Add Theft Case</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="theftForm"><div class="mb-3"><label class="form-label">Date</label><input type="date" class="form-control" id="theftDate" required></div><div class="mb-3"><label class="form-label">Item</label><input type="text" class="form-control" id="theftItem" required></div><div class="mb-3"><label class="form-label">Value</label><input type="number" class="form-control" id="theftVal" required></div><div class="mb-3"><label class="form-label">Description</label><textarea class="form-control" id="theftDesc" rows="3" required></textarea></div><button type="submit" class="btn btn-primary">Save</button></form></div></div></div></div>`;
    setTimeout(() => { if ($.fn.dataTable.isDataTable('#theftTable')) { $('#theftTable').DataTable().destroy(); } $('#theftTable').DataTable({pageLength: 10}); }, 100);
    return html;
}
function showTheftForm() { document.getElementById('theftForm').reset(); new bootstrap.Modal(document.getElementById('theftModal')).show(); }
function deleteTheft(id) { if (confirm('Sure?')) { let t = loadData('theft'); t = t.filter(x => x.id !== id); saveData('theft', t); showAlert('Deleted', 'success'); loadModule('theft'); } }
document.addEventListener('DOMContentLoaded', () => { if (document.getElementById('theftForm')) { document.getElementById('theftForm').addEventListener('submit', (e) => { e.preventDefault(); let theft = loadData('theft'); theft.push({id: Math.max(...theft.map(x => x.id), 0) + 1, caseNo: 'THEFT-' + Date.now(), date: document.getElementById('theftDate').value, item: document.getElementById('theftItem').value, value: document.getElementById('theftVal').value, description: document.getElementById('theftDesc').value, status: 'open'}); saveData('theft', theft); bootstrap.Modal.getInstance(document.getElementById('theftModal')).hide(); showAlert('Saved', 'success'); loadModule('theft'); }); } });
