// Violations Module
function loadViolations() {
    const violations = loadData('violations') || [];
    const html = `<div class="card"><div class="card-header d-flex justify-content-between"><span>Violations</span><button class="btn btn-sm btn-light" onclick="showViolationForm()"><i class="fas fa-plus"></i> Add</button></div><div class="card-body"><table class="table table-striped" id="violTable"><thead><tr><th>No</th><th>Employee</th><th>Type</th><th>Date</th><th>Penalty</th><th>Status</th><th>Actions</th></tr></thead><tbody>${violations.map(v => `<tr><td>${v.violNo}</td><td>${v.employee}</td><td>${v.type}</td><td>${v.date}</td><td>${v.penalty}</td><td><span class="badge bg-info">${v.status}</span></td><td><button class="btn btn-sm btn-danger" onclick="deleteViolation(${v.id})"><i class="fas fa-trash"></i></button></td></tr>`).join('')}</tbody></table></div></div><div class="modal fade" id="violModal"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Add Violation</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="violForm"><div class="mb-3"><label class="form-label">Employee</label><input type="text" class="form-control" id="violEmp" required></div><div class="mb-3"><label class="form-label">Type</label><select class="form-select" id="violType" required><option>Select</option><option value="safety">Safety</option><option value="conduct">Conduct</option><option value="attendance">Attendance</option></select></div><div class="mb-3"><label class="form-label">Date</label><input type="date" class="form-control" id="violDate" required></div><div class="mb-3"><label class="form-label">Penalty</label><input type="text" class="form-control" id="violPen" required></div><button type="submit" class="btn btn-primary">Save</button></form></div></div></div></div>`;
    setTimeout(() => { if ($.fn.dataTable.isDataTable('#violTable')) { $('#violTable').DataTable().destroy(); } $('#violTable').DataTable({pageLength: 10}); }, 100);
    return html;
}
function showViolationForm() { document.getElementById('violForm').reset(); new bootstrap.Modal(document.getElementById('violModal')).show(); }
function deleteViolation(id) { if (confirm('Sure?')) { let v = loadData('violations'); v = v.filter(x => x.id !== id); saveData('violations', v); showAlert('Deleted', 'success'); loadModule('violations'); } }
document.addEventListener('DOMContentLoaded', () => { if (document.getElementById('violForm')) { document.getElementById('violForm').addEventListener('submit', (e) => { e.preventDefault(); let violations = loadData('violations'); violations.push({id: Math.max(...violations.map(x => x.id), 0) + 1, violNo: 'VIO-' + Date.now(), employee: document.getElementById('violEmp').value, type: document.getElementById('violType').value, date: document.getElementById('violDate').value, penalty: document.getElementById('violPen').value, status: 'open'}); saveData('violations', violations); bootstrap.Modal.getInstance(document.getElementById('violModal')).hide(); showAlert('Saved', 'success'); loadModule('violations'); }); } });
